version: '3.8'
services:
  backend:
    build: ./backend
    environment:
      - MONGO_URI=mongodb://db:27017/lunchsync
      - JWT_SECRET=changeme
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:3000
    ports:
      - "8080:80"
    depends_on:
      - backend
  db:
    image: mongo:latest
    volumes:
      - db_data:/data/db
    ports:
      - "27017:27017"
volumes:
  db_data:
